project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
files:
  - source: template.pot
    translation: /%two_letters_code%.po
  - source: mod/mod_names_en.json
    translation: mod/mod_names_%two_letters_code%.json
    scheme: identifier_based
    type: json
