name: Build Pages

on:
  workflow_dispatch: # allow manual trigger
  push:
    branches:
      - main
    paths:
      - "**.po"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qttools5-dev-tools gettext

      - name: Build translations
        run: |
          ./release.sh

      - name: Move directory
        run: |
          mkdir -p MiniSkins/translations
          mv build/* MiniSkins/translations

      # 设置 AWS 凭证
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          # 设置 AWS 凭证过期时间，默认为 1 小时
          expires-in: 3600

      # 将目录同步到 S3
      - name: Sync to S3
        run: |
          aws s3 sync ./MiniSkins/translations s3://${{ secrets.AWS_S3_Name }}/translations --delete
