name: Build Pages

on:
  workflow_dispatch: # allow manual trigger
  push:
    branches:
      - main
    paths:
      - '**.po'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qttools5-dev-tools gettext

      - name: Build translations
        run: |
          ./release.sh

      - name: Move directory
        run: |
          mkdir -p MiniSkins/translations
          mv build MiniSkins/translations
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@main
        with:
          name: miniskins
          path: ./MiniSkins
      - name: Upload qiniu
        run: |
          curl -L https://github.com/qiniu/qshell/releases/download/v2.14.0/qshell-v2.14.0-linux-386.tar.gz -o qshell.tar.gz
          tar -zxvf qshell.tar.gz
          chmod +x qshell
          ./qshell account ${{ secrets.AK }} ${{ secrets.SK }} bs
          ./qshell qupload2 --src-dir=./MiniSkins --bucket=${{ secrets.QINIU_Name }} --up-host=http://upload-z2.qiniu.com --overwrite=true --rescan-local=true
